# Generated by Django 6.0.4 on 2026-05-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blogcategory_alter_brand_id_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='banner_color',
            field=models.CharField(blank=True, default='#0d0d0d', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='font_family',
            field=models.CharField(blank=True, default='georgia', max_length=30),
        ),
    ]
